import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/ai_conversation_model.dart';
import '../models/ai_message_model.dart';

/// Repository responsible for communication with the LifeLynk AI backend.
///
/// AI flow:
///
/// Flutter
///   -> FastAPI /api/v1/ai/chat
///   -> Supabase JWT verification
///   -> real LifeLynk PostgreSQL data
///   -> Ollama / Gemma 3 4B
///   -> AI response
///
/// The Flutter application never communicates with Ollama directly.
class AiRepository {
  AiRepository({
    String? baseUrl,
    http.Client? client,
    SupabaseClient? supabase,
  })  : _baseUrl = (baseUrl ?? _defaultBaseUrl).replaceFirst(
          RegExp(r'/$'),
          '',
        ),
        _client = client ?? http.Client(),
        _supabase = supabase ?? Supabase.instance.client;

  static const String _defaultBaseUrl =
      'https://mooned-supreme-exalted.ngrok-free.dev/api/v1';

  static const Duration _requestTimeout = Duration(minutes: 5);

  final String _baseUrl;
  final http.Client _client;
  final SupabaseClient _supabase;

  /// Local conversation cache.
  ///
  /// The actual AI response is generated by the backend.
  /// Conversation history for the current UI session is maintained here
  /// so the existing presentation layer can continue to work.
  final List<AiConversationModel> _conversations = [];

  // ---------------------------------------------------------------------------
  // Conversation management
  // ---------------------------------------------------------------------------

  /// Returns all conversations currently available to the UI.
  Future<List<AiConversationModel>> getConversations() async {
    final conversations = List<AiConversationModel>.from(
      _conversations,
    );

    conversations.sort(
      (a, b) => b.updatedAt.compareTo(a.updatedAt),
    );

    return conversations;
  }

  /// Returns a conversation by ID.
  Future<AiConversationModel?> getConversation(
    String conversationId,
  ) async {
    for (final conversation in _conversations) {
      if (conversation.id == conversationId) {
        return conversation;
      }
    }

    return null;
  }

  /// Creates a new conversation.
  Future<AiConversationModel> createConversation() async {
    final conversation = AiConversationModel.create();

    _conversations.insert(
      0,
      conversation,
    );

    return conversation;
  }

  /// Saves or updates a conversation.
  Future<AiConversationModel> saveConversation(
    AiConversationModel conversation,
  ) async {
    final index = _conversations.indexWhere(
      (item) => item.id == conversation.id,
    );

    if (index == -1) {
      _conversations.insert(
        0,
        conversation,
      );
    } else {
      _conversations[index] = conversation;
    }

    return conversation;
  }

  /// Deletes a conversation from the current application session.
  ///
  /// AI chat history is also persisted by the FastAPI backend in
  /// `ai_chat_history`. This method only controls the local UI cache.
  Future<bool> deleteConversation(
    String conversationId,
  ) async {
    final previousLength = _conversations.length;

    _conversations.removeWhere(
      (conversation) => conversation.id == conversationId,
    );

    return _conversations.length < previousLength;
  }

  /// Deletes all conversations from the current application session.
  Future<void> clearConversations() async {
    _conversations.clear();
  }

  // ---------------------------------------------------------------------------
  // AI
  // ---------------------------------------------------------------------------

  /// Sends a message to the real LifeLynk AI backend.
  ///
  /// The Supabase access token is attached as a Bearer token.
  ///
  /// The backend is responsible for:
  /// - authenticating the user
  /// - retrieving trusted LifeLynk data
  /// - sending the trusted context to Gemma
  /// - calling local Ollama
  /// - storing the successful response in ai_chat_history
  Future<AiMessageModel> sendMessage({
    required String message,
    required AiConversationModel conversation,
  }) async {
    final normalizedMessage = message.trim();

    if (normalizedMessage.isEmpty) {
      throw const AiRepositoryException(
        'Please enter a message so I can help you.',
      );
    }

    final session = _supabase.auth.currentSession;

    if (session == null) {
      throw const AiRepositoryException(
        'Your session has expired. Please sign in again.',
      );
    }

    final accessToken = session.accessToken.trim();

    if (accessToken.isEmpty) {
      throw const AiRepositoryException(
        'Authentication token is unavailable. Please sign in again.',
      );
    }

    final conversationMessages = _buildConversationMessages(
      conversation,
    );

    final uri = Uri.parse(
      '$_baseUrl/ai/chat',
    );

    final requestBody = <String, dynamic>{
      'message': normalizedMessage,
      'conversation': conversationMessages,
      'context': null,
    };

    try {
      final response = await _client
          .post(
            uri,
            headers: <String, String>{
              'Content-Type': 'application/json',
              'Accept': 'application/json',
              'Authorization': 'Bearer $accessToken',
            },
            body: jsonEncode(requestBody),
          )
          .timeout(_requestTimeout);

      return _parseChatResponse(response);
    } on AiRepositoryException {
      rethrow;
    } on FormatException catch (error) {
      throw AiRepositoryException(
        'The AI server returned an invalid response: ${error.message}',
      );
    } on http.ClientException catch (error) {
      throw AiRepositoryException(
        'Could not connect to the LifeLynk AI server: ${error.message}',
      );
    } on Exception catch (error) {
      final message = error.toString();

      if (message.contains('TimeoutException')) {
        throw const AiRepositoryException(
          'The AI is taking too long to respond. '
          'Please try again in a moment.',
        );
      }

      throw AiRepositoryException(
        'Unable to contact LifeLynk AI: $error',
      );
    }
  }

  /// Converts the existing conversation model into the API format.
  ///
  /// Only user/assistant messages should be sent to the backend.
  List<Map<String, String>> _buildConversationMessages(
    AiConversationModel conversation,
  ) {
    final messages = <Map<String, String>>[];

    for (final message in conversation.messages) {
      final content = message.content.trim();

      if (content.isEmpty) {
        continue;
      }

      final role = _normalizeMessageRole(
        message.role,
      );

      if (role == null) {
        continue;
      }

      messages.add(
        <String, String>{
          'role': role,
          'content': content,
        },
      );
    }

    // Keep the request reasonably small. The backend also applies its
    // own conversation limit before sending messages to Gemma.
    if (messages.length > 20) {
      return messages.sublist(
        messages.length - 20,
      );
    }

    return messages;
  }

  String? _normalizeMessageRole(
    dynamic role,
  ) {
    final normalized = role.toString().trim().toLowerCase();

    if (normalized == 'user') {
      return 'user';
    }

    if (normalized == 'assistant') {
      return 'assistant';
    }

    return null;
  }

  /// Parses a successful or failed FastAPI response.
  AiMessageModel _parseChatResponse(
    http.Response response,
  ) {
    dynamic decoded;

    try {
      decoded = jsonDecode(response.body);
    } on FormatException {
      throw AiRepositoryException(
        'The AI server returned an invalid JSON response '
        '(HTTP ${response.statusCode}).',
      );
    }

    if (response.statusCode >= 200 &&
        response.statusCode < 300) {
      if (decoded is! Map<String, dynamic>) {
        throw const AiRepositoryException(
          'The AI server returned an unexpected response.',
        );
      }

      final responseText = decoded['response'];

      if (responseText is! String ||
          responseText.trim().isEmpty) {
        throw const AiRepositoryException(
          'The AI server returned an empty response.',
        );
      }

      return AiMessageModel.assistant(
        content: responseText.trim(),
      );
    }

    throw AiRepositoryException(
      _extractBackendError(
        response.statusCode,
        decoded,
      ),
    );
  }

  String _extractBackendError(
    int statusCode,
    dynamic decoded,
  ) {
    String? detail;

    if (decoded is Map<String, dynamic>) {
      final value = decoded['detail'];

      if (value is String) {
        detail = value.trim();
      } else if (value is List && value.isNotEmpty) {
        detail = value
            .map(
              (item) => item.toString(),
            )
            .join(', ')
            .trim();
      }
    }

    if (detail != null && detail.isNotEmpty) {
      return detail;
    }

    switch (statusCode) {
      case 401:
        return 'Your session is invalid or has expired. '
            'Please sign in again.';

      case 403:
        return 'You do not have permission to use LifeLynk AI.';

      case 400:
        return 'The AI request was invalid. Please try again.';

      case 404:
        return 'The LifeLynk AI endpoint could not be found.';

      case 503:
        return 'LifeLynk AI is temporarily unavailable. '
            'Please make sure the local AI service is running.';

      default:
        return 'LifeLynk AI returned an error '
            '(HTTP $statusCode).';
    }
  }

  /// Releases the HTTP client.
  ///
  /// Call this only if the repository is owned by a lifecycle that
  /// explicitly manages the repository instance.
  void dispose() {
    _client.close();
  }
}


/// Exception thrown when the LifeLynk AI repository cannot complete
/// an AI operation.
class AiRepositoryException implements Exception {
  const AiRepositoryException(this.message);

  final String message;

  @override
  String toString() => message;
}

