"""create_blood_requests_table

Revision ID: 1b1977da84db
Revises: dc3bee8f16fb
Create Date: 2026-08-02 04:49:55.996103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1977da84db'
down_revision: Union[str, Sequence[str], None] = 'dc3bee8f16fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('blood_group_id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('units_required', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('required_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('patient_age IS NULL OR patient_age > 0', name=op.f('ck_blood_requests_check_patient_age_positive')),
    sa.CheckConstraint('units_required > 0', name=op.f('ck_blood_requests_check_units_required_positive')),
    sa.ForeignKeyConstraint(['blood_group_id'], ['blood_groups.id'], name=op.f('fk_blood_requests_blood_group_id_blood_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_blood_requests_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_blood_requests_requester_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blood_requests'))
    )
    op.create_index('ix_blood_requests_search', 'blood_requests', ['blood_group_id', 'organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blood_requests_search', table_name='blood_requests')
    op.drop_table('blood_requests')
    # ### end Alembic commands ###
