"""Add latitude and longitude to cities

Revision ID: 2f40a5791bd6
Revises: 355085d59b13
Create Date: 2026-08-03 09:27:41.749464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f40a5791bd6'
down_revision: Union[str, Sequence[str], None] = '355085d59b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('cities', sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.create_index(op.f('ix_cities_province_id'), 'cities', ['province_id'], unique=False)
    op.create_index('ix_cities_province_name', 'cities', ['province_id', 'name'], unique=False)
    op.create_unique_constraint(op.f('uq_cities_code'), 'cities', ['code'])
    op.create_unique_constraint('uq_city_province_name', 'cities', ['province_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_city_province_name', 'cities', type_='unique')
    op.drop_constraint(op.f('uq_cities_code'), 'cities', type_='unique')
    op.drop_index('ix_cities_province_name', table_name='cities')
    op.drop_index(op.f('ix_cities_province_id'), table_name='cities')
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.drop_column('cities', 'longitude')
    op.drop_column('cities', 'latitude')
    # ### end Alembic commands ###
