"""create_blood_groups_table

Revision ID: 494de877eaf8
Revises: e6320ed6213d
Create Date: 2026-08-02 04:35:41.784167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494de877eaf8'
down_revision: Union[str, Sequence[str], None] = 'e6320ed6213d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_groups',
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blood_groups')),
    sa.UniqueConstraint('code', name=op.f('uq_blood_groups_code')),
    sa.UniqueConstraint('name', name=op.f('uq_blood_groups_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blood_groups')
    # ### end Alembic commands ###
