"""create_donor_matches_table

Revision ID: 5dd43276b705
Revises: d65ed8f048a4
Create Date: 2026-08-02 05:03:43.904083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd43276b705'
down_revision: Union[str, Sequence[str], None] = 'd65ed8f048a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blood_request_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('ai_reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blood_request_id'], ['blood_requests.id'], name=op.f('fk_donor_matches_blood_request_id_blood_requests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], name=op.f('fk_donor_matches_donor_id_donors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donor_matches'))
    )
    op.create_index('ix_donor_matches_request_score', 'donor_matches', ['blood_request_id', 'compatibility_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_donor_matches_request_score', table_name='donor_matches')
    op.drop_table('donor_matches')
    # ### end Alembic commands ###
