"""create_hospitals_table

Revision ID: 69d8b93cd572
Revises: 1f9a522948ec
Create Date: 2026-08-02 04:28:57.101765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d8b93cd572'
down_revision: Union[str, Sequence[str], None] = '1f9a522948ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('hospital_type', sa.String(length=50), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('emergency_service', sa.Boolean(), nullable=False),
    sa.Column('blood_storage_available', sa.Boolean(), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=True),
    sa.Column('icu_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_hospitals_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospitals')),
    sa.UniqueConstraint('license_number', name=op.f('uq_hospitals_license_number')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_hospitals_organization_id'))
    )
    op.create_index('ix_hospitals_license_number', 'hospitals', ['license_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hospitals_license_number', table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
