"""create_donor_availability_table

Revision ID: 9669641957a1
Revises: cee4dc8fec68
Create Date: 2026-08-02 04:59:58.257266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9669641957a1'
down_revision: Union[str, Sequence[str], None] = 'cee4dc8fec68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_eligible_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], name=op.f('fk_donor_availability_donor_id_donors'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donor_availability')),
    sa.UniqueConstraint('donor_id', name=op.f('uq_donor_availability_donor_id'))
    )
    op.create_index('ix_donor_availability_search', 'donor_availability', ['is_available', 'next_eligible_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_donor_availability_search', table_name='donor_availability')
    op.drop_table('donor_availability')
    # ### end Alembic commands ###
