"""create_government_analytics_table

Revision ID: a61b4558ba93
Revises: a15e04907035
Create Date: 2026-08-02 05:10:35.012739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61b4558ba93'
down_revision: Union[str, Sequence[str], None] = 'a15e04907035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_government_analytics'))
    )
    op.create_index('ix_government_analytics_metric_region', 'government_analytics', ['metric_name', 'region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_government_analytics_metric_region', table_name='government_analytics')
    op.drop_table('government_analytics')
    # ### end Alembic commands ###
