"""add patients and organization staff

Revision ID: b359f667ccef
Revises: dc74955e1860
Create Date: 2026-08-02 18:17:49.333898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b359f667ccef'
down_revision: Union[str, Sequence[str], None] = 'dc74955e1860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('blood_group_id', sa.UUID(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('medical_notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blood_group_id'], ['blood_groups.id'], name=op.f('fk_patients_blood_group_id_blood_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_patients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patients_user_id'))
    )
    op.create_table('organization_staff',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_staff_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_staff_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_staff'))
    )
    op.add_column('blood_requests', sa.Column('patient_id', sa.UUID(), nullable=False))
    op.add_column('blood_requests', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_blood_requests_patient_id_patients'), 'blood_requests', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('blood_requests', 'patient_age')
    op.drop_column('blood_requests', 'patient_name')
    op.drop_column('blood_requests', 'contact_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_requests', sa.Column('contact_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('blood_requests', sa.Column('patient_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('blood_requests', sa.Column('patient_age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_blood_requests_patient_id_patients'), 'blood_requests', type_='foreignkey')
    op.drop_column('blood_requests', 'deleted_at')
    op.drop_column('blood_requests', 'patient_id')
    op.drop_table('organization_staff')
    op.drop_table('patients')
    # ### end Alembic commands ###
