"""create_donors_table

Revision ID: cee4dc8fec68
Revises: ef9ded3f823a
Create Date: 2026-08-02 04:58:21.369342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee4dc8fec68'
down_revision: Union[str, Sequence[str], None] = 'ef9ded3f823a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('blood_group_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('total_donations', sa.Integer(), nullable=False),
    sa.Column('last_donation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blood_group_id'], ['blood_groups.id'], name=op.f('fk_donors_blood_group_id_blood_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_donors_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_donors_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donors')),
    sa.UniqueConstraint('user_id', name=op.f('uq_donors_user_id'))
    )
    op.create_index('ix_donors_matching_search', 'donors', ['blood_group_id', 'city_id', 'is_available'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_donors_matching_search', table_name='donors')
    op.drop_table('donors')
    # ### end Alembic commands ###
