"""create_donation_history_table

Revision ID: d65ed8f048a4
Revises: 9669641957a1
Create Date: 2026-08-02 05:01:42.824589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65ed8f048a4'
down_revision: Union[str, Sequence[str], None] = '9669641957a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('blood_group_id', sa.UUID(), nullable=False),
    sa.Column('units_donated', sa.Integer(), nullable=False),
    sa.Column('donation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('units_donated > 0', name=op.f('ck_donation_history_check_units_donated_positive')),
    sa.ForeignKeyConstraint(['blood_group_id'], ['blood_groups.id'], name=op.f('fk_donation_history_blood_group_id_blood_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], name=op.f('fk_donation_history_donor_id_donors'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_donation_history_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donation_history'))
    )
    op.create_index('ix_donation_history_donor_date', 'donation_history', ['donor_id', 'donation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_donation_history_donor_date', table_name='donation_history')
    op.drop_table('donation_history')
    # ### end Alembic commands ###
