"""create_blood_inventory_table

Revision ID: dc3bee8f16fb
Revises: 494de877eaf8
Create Date: 2026-08-02 04:44:46.674021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc3bee8f16fb'
down_revision: Union[str, Sequence[str], None] = '494de877eaf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('blood_group_id', sa.UUID(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('available_units', sa.Integer(), nullable=False),
    sa.Column('reserved_units', sa.Integer(), nullable=False),
    sa.Column('donation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_units + reserved_units <= total_units', name=op.f('ck_blood_inventory_check_inventory_balance')),
    sa.CheckConstraint('available_units >= 0', name=op.f('ck_blood_inventory_check_available_units_positive')),
    sa.CheckConstraint('reserved_units >= 0', name=op.f('ck_blood_inventory_check_reserved_units_positive')),
    sa.CheckConstraint('total_units >= 0', name=op.f('ck_blood_inventory_check_total_units_positive')),
    sa.ForeignKeyConstraint(['blood_group_id'], ['blood_groups.id'], name=op.f('fk_blood_inventory_blood_group_id_blood_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_blood_inventory_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blood_inventory'))
    )
    op.create_index('ix_blood_inventory_org_group', 'blood_inventory', ['organization_id', 'blood_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blood_inventory_org_group', table_name='blood_inventory')
    op.drop_table('blood_inventory')
    # ### end Alembic commands ###
