"""create_emergency_sos_table

Revision ID: dc74955e1860
Revises: a61b4558ba93
Create Date: 2026-08-02 05:12:02.483009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc74955e1860'
down_revision: Union[str, Sequence[str], None] = 'a61b4558ba93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_sos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('blood_group_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('units_required', sa.Integer(), nullable=False),
    sa.Column('urgency_level', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blood_group_id'], ['blood_groups.id'], name=op.f('fk_emergency_sos_blood_group_id_blood_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_emergency_sos_city_id_cities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emergency_sos_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_sos'))
    )
    op.create_index('ix_emergency_sos_search', 'emergency_sos', ['blood_group_id', 'city_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emergency_sos_search', table_name='emergency_sos')
    op.drop_table('emergency_sos')
    # ### end Alembic commands ###
