"""create_blood_banks_table

Revision ID: e6320ed6213d
Revises: 69d8b93cd572
Create Date: 2026-08-02 04:31:52.780631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6320ed6213d'
down_revision: Union[str, Sequence[str], None] = '69d8b93cd572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_banks',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('storage_capacity', sa.Integer(), nullable=True),
    sa.Column('cold_storage_available', sa.Boolean(), nullable=False),
    sa.Column('blood_processing_available', sa.Boolean(), nullable=False),
    sa.Column('operating_hours', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_blood_banks_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blood_banks')),
    sa.UniqueConstraint('license_number', name=op.f('uq_blood_banks_license_number')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_blood_banks_organization_id'))
    )
    op.create_index('ix_blood_banks_license_number', 'blood_banks', ['license_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blood_banks_license_number', table_name='blood_banks')
    op.drop_table('blood_banks')
    # ### end Alembic commands ###
