"""create_blood_reservations_table

Revision ID: ef9ded3f823a
Revises: 1b1977da84db
Create Date: 2026-08-02 04:53:45.461765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9ded3f823a'
down_revision: Union[str, Sequence[str], None] = '1b1977da84db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blood_request_id', sa.UUID(), nullable=False),
    sa.Column('blood_inventory_id', sa.UUID(), nullable=False),
    sa.Column('units_reserved', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('units_reserved > 0', name=op.f('ck_blood_reservations_check_reserved_units_positive')),
    sa.ForeignKeyConstraint(['blood_inventory_id'], ['blood_inventory.id'], name=op.f('fk_blood_reservations_blood_inventory_id_blood_inventory'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['blood_request_id'], ['blood_requests.id'], name=op.f('fk_blood_reservations_blood_request_id_blood_requests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blood_reservations'))
    )
    op.create_index('ix_blood_reservations_request_status', 'blood_reservations', ['blood_request_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blood_reservations_request_status', table_name='blood_reservations')
    op.drop_table('blood_reservations')
    # ### end Alembic commands ###
