"""create_provinces_table

Revision ID: fb0f9f9effec
Revises: bb58de3640df
Create Date: 2026-08-02 04:13:10.438718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0f9f9effec'
down_revision: Union[str, Sequence[str], None] = 'bb58de3640df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provinces')),
    sa.UniqueConstraint('code', name=op.f('uq_provinces_code')),
    sa.UniqueConstraint('name', name=op.f('uq_provinces_name'))
    )
    op.create_index('ix_provinces_name', 'provinces', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provinces_name', table_name='provinces')
    op.drop_table('provinces')
    # ### end Alembic commands ###
