from enum import Enum


class NotificationType(str, Enum):
    RESERVATION_CREATED = "RESERVATION_CREATED"
    RESERVATION_APPROVED = "RESERVATION_APPROVED"
    RESERVATION_REJECTED = "RESERVATION_REJECTED"
    RESERVATION_CANCELLED = "RESERVATION_CANCELLED"
    EMERGENCY_CREATED = "EMERGENCY_CREATED"
    EMERGENCY_ACCEPTED = "EMERGENCY_ACCEPTED"
    EMERGENCY_REJECTED = "EMERGENCY_REJECTED"
    LOW_BLOOD_STOCK = "LOW_BLOOD_STOCK"
    INVENTORY_UPDATED = "INVENTORY_UPDATED"
    SYSTEM_ANNOUNCEMENT = "SYSTEM_ANNOUNCEMENT"
    ACCOUNT_SECURITY = "ACCOUNT_SECURITY"