"use client";

import {
  useCallback,
  useEffect,
  useMemo,
  useState,
} from "react";

import { useRouter } from "next/navigation";

import "./emergency-sos.css";

import {
  updateEmergencySosStatus,
  type EmergencySosStatus,
} from "@/lib/dashboard/emergency-sos-actions";

import type {
  EmergencySosData,
  EmergencySosRecord,
} from "@/lib/dashboard/get-emergency-sos-data";

import { createClient } from "@/lib/supabase/client";

interface EmergencySosClientProps {
  data: EmergencySosData;
  userRole: string;
}

type FilterType =
  | "ALL"
  | "ACTIVE"
  | "PENDING"
  | "COMPLETED"
  | "CANCELLED";

type ActionType =
  | "MATCHED"
  | "IN_PROGRESS"
  | "COMPLETED"
  | "CANCELLED";

/* =========================================================
   HELPERS
   ========================================================= */

function normalizedStatus(status: string): string {
  return status.trim().toLowerCase();
}

function formatStatus(status: string): string {
  switch (normalizedStatus(status)) {
    case "pending":
      return "Pending";

    case "matched":
      return "Matched";

    case "in_progress":
      return "In Progress";

    case "completed":
      return "Completed";

    case "cancelled":
      return "Cancelled";

    default:
      return status
        .replace(/_/g, " ")
        .replace(/\b\w/g, (character) =>
          character.toUpperCase(),
        );
  }
}

function formatUrgency(urgency: string): string {
  return urgency
    .replace(/_/g, " ")
    .replace(/\b\w/g, (character) =>
      character.toUpperCase(),
    );
}

function formatDate(
  value: string | null | undefined,
): string {
  if (!value) {
    return "—";
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "—";
  }

  return date.toLocaleString();
}

function formatCoordinate(
  value: number | null | undefined,
): string {
  if (
    value === null ||
    value === undefined
  ) {
    return "—";
  }

  return value.toFixed(6);
}

function getUser(
  record: EmergencySosRecord,
) {
  return record.users?.[0] ?? null;
}

function getBloodGroup(
  record: EmergencySosRecord,
) {
  return record.blood_groups?.[0] ?? null;
}

function getCity(
  record: EmergencySosRecord,
) {
  return record.cities?.[0] ?? null;
}

function getProvince(
  record: EmergencySosRecord,
) {
  return (
    getCity(record)?.provinces?.[0] ??
    null
  );
}

function getLocationText(
  record: EmergencySosRecord,
): string {
  const city = getCity(record);
  const province = getProvince(record);

  if (city && province) {
    return `${city.name}, ${province.name}`;
  }

  if (city) {
    return city.name;
  }

  return "Location unavailable";
}

function getStatusClass(
  status: string,
): string {
  switch (normalizedStatus(status)) {
    case "pending":
      return "pending";

    case "matched":
      return "active";

    case "in_progress":
      return "active";

    case "completed":
      return "resolved";

    case "cancelled":
      return "cancelled";

    default:
      return "";
  }
}

function canMatch(
  status: string,
): boolean {
  return (
    normalizedStatus(status) ===
    "pending"
  );
}

function canStartResponse(
  status: string,
): boolean {
  return (
    normalizedStatus(status) ===
    "matched"
  );
}

function canComplete(
  status: string,
): boolean {
  return (
    normalizedStatus(status) ===
    "in_progress"
  );
}

function canCancel(
  status: string,
): boolean {
  const value =
    normalizedStatus(status);

  return (
    value === "pending" ||
    value === "matched" ||
    value === "in_progress"
  );
}

function hasCoordinates(
  record: EmergencySosRecord,
): boolean {
  return (
    record.latitude !== null &&
    record.latitude !== undefined &&
    record.longitude !== null &&
    record.longitude !== undefined
  );
}

/* =========================================================
   OPENSTREETMAP
   ========================================================= */

function getOpenStreetMapUrl(
  record: EmergencySosRecord,
): string | null {
  if (!hasCoordinates(record)) {
    return null;
  }

  return (
    "https://www.openstreetmap.org/" +
    `?mlat=${record.latitude}` +
    `&mlon=${record.longitude}` +
    `#map=16/${record.latitude}/${record.longitude}`
  );
}

function getOpenStreetMapEmbedUrl(
  record: EmergencySosRecord,
): string | null {
  if (!hasCoordinates(record)) {
    return null;
  }

  const latitude = record.latitude!;
  const longitude = record.longitude!;

  /*
   * Small bounding box around the actual SOS GPS point.
   * The marker is generated by OpenStreetMap itself.
   */
  const delta = 0.01;

  const left = longitude - delta;
  const right = longitude + delta;
  const top = latitude + delta;
  const bottom = latitude - delta;

  return (
    "https://www.openstreetmap.org/export/embed.html" +
    `?bbox=${left},${bottom},${right},${top}` +
    "&layer=mapnik" +
    `&marker=${latitude},${longitude}`
  );
}

/* =========================================================
   COMPONENT
   ========================================================= */

export default function EmergencySosClient({
  data,
  userRole,
}: EmergencySosClientProps) {
  const router = useRouter();

  const [
    realtimeConnected,
    setRealtimeConnected,
  ] = useState(false);

  const [
    realtimeError,
    setRealtimeError,
  ] = useState<string | null>(null);

  const [filter, setFilter] =
    useState<FilterType>("ALL");

  const [search, setSearch] =
    useState("");

  const [selected, setSelected] =
    useState<EmergencySosRecord | null>(
      null,
    );

  const [actionLoading, setActionLoading] =
    useState<ActionType | null>(null);

  const [actionError, setActionError] =
    useState<string | null>(null);

  const [actionSuccess, setActionSuccess] =
    useState<string | null>(null);

  const records = data.records ?? [];

  /* =======================================================
     REALTIME SUPABASE SUBSCRIPTION
     ======================================================= */

  const refreshEmergencySos =
    useCallback(() => {
      /*
       * Re-run the server component so the UI receives
       * complete relational data:
       *
       * emergency_sos
       * + users
       * + blood_groups
       * + cities
       * + provinces
       *
       * We deliberately do not construct fake/incomplete
       * records from the realtime payload.
       */
      router.refresh();
    }, [router]);

  useEffect(() => {
    const supabase = createClient();

    const channel = supabase
      .channel(
        "emergency-sos-dashboard-realtime",
      )
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "emergency_sos",
        },
        (payload) => {
          console.log(
            "Emergency SOS realtime event:",
            payload.eventType,
            payload,
          );

          /*
           * Realtime payload contains the emergency_sos
           * row but not the relational records used by
           * this page.
           *
           * Therefore refresh the server component.
           */
          refreshEmergencySos();
        },
      )
      .subscribe((status) => {
        console.log(
          "Emergency SOS realtime status:",
          status,
        );

        if (status === "SUBSCRIBED") {
          setRealtimeConnected(true);
          setRealtimeError(null);
          return;
        }

        if (
          status === "CHANNEL_ERROR"
        ) {
          setRealtimeConnected(false);

          setRealtimeError(
            "Emergency SOS realtime connection failed.",
          );

          return;
        }

        if (
          status === "TIMED_OUT"
        ) {
          setRealtimeConnected(false);

          setRealtimeError(
            "Emergency SOS realtime connection timed out.",
          );

          return;
        }

        if (
          status === "CLOSED"
        ) {
          setRealtimeConnected(false);
        }
      });

    return () => {
      setRealtimeConnected(false);

      void supabase.removeChannel(
        channel,
      );
    };
  }, [refreshEmergencySos]);

  /* =======================================================
     KEEP SELECTED RECORD SYNCHRONIZED
     ======================================================= */

  useEffect(() => {
    if (!selected) {
      return;
    }

    const updatedSelected =
      records.find(
        (record) =>
          record.id === selected.id,
      );

    /*
     * If the selected SOS no longer exists,
     * close the details modal.
     */
    if (!updatedSelected) {
      setSelected(null);
      return;
    }

    /*
     * IMPORTANT:
     *
     * Depend on selected?.id rather than the complete
     * selected object. This prevents the effect from
     * repeatedly replacing selected with a new object.
     */
    setSelected(updatedSelected);
  }, [records, selected?.id]);

  /* =======================================================
     FILTERING
     ======================================================= */

  const filteredRecords = useMemo(() => {
    const query =
      search.trim().toLowerCase();

    return records.filter((record) => {
      const status =
        normalizedStatus(record.status);

      let matchesFilter = true;

      switch (filter) {
        case "ACTIVE":
          matchesFilter =
            status === "pending" ||
            status === "matched" ||
            status === "in_progress";
          break;

        case "PENDING":
          matchesFilter =
            status === "pending";
          break;

        case "COMPLETED":
          matchesFilter =
            status === "completed";
          break;

        case "CANCELLED":
          matchesFilter =
            status === "cancelled";
          break;

        case "ALL":
        default:
          matchesFilter = true;
          break;
      }

      if (!matchesFilter) {
        return false;
      }

      if (!query) {
        return true;
      }

      const user = getUser(record);

      const bloodGroup =
        getBloodGroup(record);

      const city = getCity(record);

      const province =
        getProvince(record);

      const searchableText = [
        record.id,
        record.user_id,
        record.blood_group_id,
        record.status,
        record.urgency_level,
        record.description ?? "",
        record.units_required.toString(),
        user?.full_name ?? "",
        user?.email ?? "",
        bloodGroup?.code ?? "",
        bloodGroup?.name ?? "",
        city?.name ?? "",
        province?.name ?? "",
      ]
        .join(" ")
        .toLowerCase();

      return searchableText.includes(
        query,
      );
    });
  }, [
    records,
    filter,
    search,
  ]);

  /* =======================================================
     STATUS ACTION
     ======================================================= */

  async function handleStatusUpdate(
    record: EmergencySosRecord,
    nextStatus: EmergencySosStatus,
    action: ActionType,
  ) {
    if (actionLoading) {
      return;
    }

    setActionLoading(action);
    setActionError(null);
    setActionSuccess(null);

    const result =
      await updateEmergencySosStatus(
        record.id,
        nextStatus,
      );

    if (!result.success) {
      setActionError(
        result.error ??
          "Unable to update the SOS request.",
      );

      setActionLoading(null);

      return;
    }

    const messages: Record<
      ActionType,
      string
    > = {
      MATCHED:
        "SOS accepted successfully. The request is now matched.",

      IN_PROGRESS:
        "SOS response is now in progress.",

      COMPLETED:
        "SOS request has been marked as completed.",

      CANCELLED:
        "SOS request has been cancelled.",
    };

    setActionSuccess(messages[action]);

    /*
     * Update the modal immediately.
     *
     * The database remains the source of truth.
     * Supabase Realtime + router.refresh()
     * will synchronize the complete record.
     */
    setSelected((current) => {
      if (!current) {
        return current;
      }

      return {
        ...current,
        status: nextStatus,
      };
    });

    setActionLoading(null);

    router.refresh();
  }

  /* =======================================================
     MODAL
     ======================================================= */

  function closeModal() {
    if (actionLoading) {
      return;
    }

    setSelected(null);
    setActionError(null);
    setActionSuccess(null);
  }

  const selectedUser =
    selected
      ? getUser(selected)
      : null;

  const selectedBloodGroup =
    selected
      ? getBloodGroup(selected)
      : null;

  const selectedLocation =
    selected
      ? getLocationText(selected)
      : "Location unavailable";

  const selectedOsmUrl =
    selected
      ? getOpenStreetMapUrl(selected)
      : null;

  const selectedOsmEmbedUrl =
    selected
      ? getOpenStreetMapEmbedUrl(
          selected,
        )
      : null;

  /* =======================================================
     RENDER
     ======================================================= */

  return (
    <div className="emergency-sos-page">

      {/* =================================================
          PAGE HEADER
          ================================================= */}

      <div className="emergency-sos-header">

        <div className="emergency-sos-heading">

          <span className="emergency-sos-eyebrow">
            LIFELYNK AI
          </span>

          <h1>
            Emergency SOS
          </h1>

          <p>
            Monitor and respond to real-time
            emergency blood requests.
          </p>

        </div>

        <div className="emergency-sos-role">

          <span>
            Current Role
          </span>

          <strong>
            {userRole}
          </strong>

        </div>

      </div>

      {/* =================================================
          REALTIME STATUS
          ================================================= */}

      <div
        className={
          realtimeConnected
            ? "sos-realtime-status sos-realtime-connected"
            : "sos-realtime-status sos-realtime-disconnected"
        }
        role="status"
        aria-live="polite"
      >

        <span className="sos-realtime-dot" />

        <span>
          {realtimeConnected
            ? "Live SOS updates connected"
            : "Connecting to live SOS updates..."}
        </span>

      </div>

      {realtimeError && (
        <div
          className="sos-alert sos-alert-error"
          role="alert"
        >

          <strong>
            Realtime unavailable
          </strong>

          <span>
            {realtimeError}
          </span>

        </div>
      )}

      {/* =================================================
          ALERTS
          ================================================= */}

      {data.error && (
        <div
          className="sos-alert sos-alert-error"
          role="alert"
        >

          <strong>
            Unable to load SOS data
          </strong>

          <span>
            {data.error}
          </span>

        </div>
      )}

      {actionError && (
        <div
          className="sos-alert sos-alert-error"
          role="alert"
        >

          <strong>
            Action failed
          </strong>

          <span>
            {actionError}
          </span>

        </div>
      )}

      {actionSuccess && (
        <div
          className="sos-alert sos-alert-success"
          role="status"
        >
          {actionSuccess}
        </div>
      )}

      {/* =================================================
          STATISTICS
          ================================================= */}

      <div className="emergency-sos-stats">

        <div className="sos-stat-card sos-stat-total">

          <span className="sos-stat-label">
            Total Requests
          </span>

          <strong className="sos-stat-value">
            {data.summary.total}
          </strong>

          <span className="sos-stat-description">
            All emergency requests
          </span>

        </div>

        <div className="sos-stat-card sos-stat-active">

          <span className="sos-stat-label">
            Active
          </span>

          <strong className="sos-stat-value">
            {data.summary.active}
          </strong>

          <span className="sos-stat-description">
            Requests requiring response
          </span>

        </div>

        <div className="sos-stat-card sos-stat-pending">

          <span className="sos-stat-label">
            Pending
          </span>

          <strong className="sos-stat-value">
            {data.summary.pending}
          </strong>

          <span className="sos-stat-description">
            Awaiting acceptance
          </span>

        </div>

        <div className="sos-stat-card sos-stat-critical">

          <span className="sos-stat-label">
            Critical
          </span>

          <strong className="sos-stat-value">
            {data.summary.critical}
          </strong>

          <span className="sos-stat-description">
            Critical urgency requests
          </span>

        </div>

        <div className="sos-stat-card sos-stat-completed">

          <span className="sos-stat-label">
            Completed
          </span>

          <strong className="sos-stat-value">
            {data.summary.resolved}
          </strong>

          <span className="sos-stat-description">
            Successfully completed
          </span>

        </div>

      </div>

      {/* =================================================
          TOOLBAR
          ================================================= */}

      <div className="emergency-sos-toolbar">

        <div className="sos-search-wrapper">

          <span className="sos-search-icon">
            ⌕
          </span>

          <input
            type="search"
            value={search}
            onChange={(event) =>
              setSearch(
                event.target.value,
              )
            }
            placeholder="Search SOS requests..."
            className="sos-search-input"
            aria-label="Search SOS requests"
          />

          {search && (
            <button
              type="button"
              className="sos-search-clear"
              onClick={() =>
                setSearch("")
              }
              aria-label="Clear search"
            >
              ×
            </button>
          )}

        </div>

        <div className="sos-filter-group">

          <button
            type="button"
            className={
              filter === "ALL"
                ? "sos-filter active"
                : "sos-filter"
            }
            onClick={() =>
              setFilter("ALL")
            }
          >
            All
          </button>

          <button
            type="button"
            className={
              filter === "ACTIVE"
                ? "sos-filter active"
                : "sos-filter"
            }
            onClick={() =>
              setFilter("ACTIVE")
            }
          >
            Active
          </button>

          <button
            type="button"
            className={
              filter === "PENDING"
                ? "sos-filter active"
                : "sos-filter"
            }
            onClick={() =>
              setFilter("PENDING")
            }
          >
            Pending
          </button>

          <button
            type="button"
            className={
              filter === "COMPLETED"
                ? "sos-filter active"
                : "sos-filter"
            }
            onClick={() =>
              setFilter("COMPLETED")
            }
          >
            Completed
          </button>

          <button
            type="button"
            className={
              filter === "CANCELLED"
                ? "sos-filter active"
                : "sos-filter"
            }
            onClick={() =>
              setFilter("CANCELLED")
            }
          >
            Cancelled
          </button>

        </div>

      </div>

      {/* =================================================
          TABLE CARD
          ================================================= */}

      <div className="emergency-sos-table-card">

        <div className="emergency-sos-table-header">

          <div>

            <span className="sos-section-eyebrow">
              REAL-TIME MONITORING
            </span>

            <h2>
              Emergency Requests
            </h2>

            <p>
              Live emergency blood requests
              available to your organization.
            </p>

          </div>

          <div className="sos-request-count">

            <strong>
              {filteredRecords.length}
            </strong>

            <span>
              {filteredRecords.length === 1
                ? "request"
                : "requests"}
            </span>

          </div>

        </div>

        {filteredRecords.length === 0 ? (

          <div className="sos-empty-state">

            <div className="sos-empty-icon">
              !
            </div>

            <h3>
              No emergency SOS requests found
            </h3>

            <p>
              There are no requests matching
              the current search or filter.
            </p>

            {(search ||
              filter !== "ALL") && (
              <button
                type="button"
                className="sos-empty-reset"
                onClick={() => {
                  setSearch("");
                  setFilter("ALL");
                }}
              >
                Clear filters
              </button>
            )}

          </div>

        ) : (

          <div className="emergency-sos-table-wrapper">

            <table className="emergency-sos-table">

              <thead>

                <tr>
                  <th>Request</th>
                  <th>Patient</th>
                  <th>Blood</th>
                  <th>Units</th>
                  <th>Urgency</th>
                  <th>Location</th>
                  <th>Status</th>
                  <th>Created</th>
                  <th>Action</th>
                </tr>

              </thead>

              <tbody>

                {filteredRecords.map(
                  (record) => {
                    const user =
                      getUser(record);

                    const bloodGroup =
                      getBloodGroup(
                        record,
                      );

                    return (
                      <tr
                        key={record.id}
                      >

                        <td>

                          <div className="sos-request-cell">

                            <div className="sos-request-icon">
                              SOS
                            </div>

                            <div className="sos-request-meta">

                              <strong>
                                {record.id.slice(
                                  0,
                                  8,
                                )}
                              </strong>

                              <span>
                                {record.id}
                              </span>

                            </div>

                          </div>

                        </td>

                        <td>

                          <div className="sos-patient-cell">

                            <strong>
                              {user?.full_name ??
                                "Unknown user"}
                            </strong>

                            <span>
                              {user?.email ??
                                "Email unavailable"}
                            </span>

                          </div>

                        </td>

                        <td>

                          <div className="sos-blood-cell">

                            <strong>
                              {bloodGroup?.code ??
                                "—"}
                            </strong>

                            <span>
                              {bloodGroup?.name ??
                                "Blood group"}
                            </span>

                          </div>

                        </td>

                        <td>

                          <span className="sos-units">
                            {record.units_required}
                          </span>

                        </td>

                        <td>

                          <span
                            className={`sos-urgency sos-urgency-${normalizedStatus(
                              record.urgency_level,
                            )}`}
                          >

                            <span className="sos-badge-dot" />

                            {formatUrgency(
                              record.urgency_level,
                            )}

                          </span>

                        </td>

                        <td>

                          <span className="sos-location-cell">
                            {getLocationText(
                              record,
                            )}
                          </span>

                        </td>

                        <td>

                          <span
                            className={`sos-status ${getStatusClass(
                              record.status,
                            )}`}
                          >

                            <span className="sos-badge-dot" />

                            {formatStatus(
                              record.status,
                            )}

                          </span>

                        </td>

                        <td>

                          <span className="sos-created">
                            {formatDate(
                              record.created_at,
                            )}
                          </span>

                        </td>

                        <td>

                          <button
                            type="button"
                            className="sos-view-button"
                            onClick={() => {
                              setActionError(
                                null,
                              );

                              setActionSuccess(
                                null,
                              );

                              setSelected(
                                record,
                              );
                            }}
                          >
                            View Details
                          </button>

                        </td>

                      </tr>
                    );
                  },
                )}

              </tbody>

            </table>

          </div>
        )}

      </div>

      {/* =================================================
          DETAILS MODAL
          ================================================= */}

      {selected && (

        <div
          className="sos-modal-backdrop"
          role="presentation"
          onMouseDown={(event) => {
            if (
              event.target ===
              event.currentTarget
            ) {
              closeModal();
            }
          }}
        >

          <div
            className="sos-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="sos-modal-title"
          >

            <div className="sos-modal-header">

              <div>

                <span className="sos-modal-eyebrow">
                  EMERGENCY SOS
                </span>

                <h2 id="sos-modal-title">
                  Request Details
                </h2>

                <p>
                  {selected.id}
                </p>

              </div>

              <button
                type="button"
                className="sos-modal-close"
                onClick={closeModal}
                disabled={
                  actionLoading !== null
                }
                aria-label="Close"
              >
                ×
              </button>

            </div>

            <div className="sos-modal-body">

              <div className="sos-detail-status-row">

                <span
                  className={`sos-status ${getStatusClass(
                    selected.status,
                  )}`}
                >

                  <span className="sos-badge-dot" />

                  {formatStatus(
                    selected.status,
                  )}

                </span>

                <span
                  className={`sos-urgency sos-urgency-${normalizedStatus(
                    selected.urgency_level,
                  )}`}
                >

                  <span className="sos-badge-dot" />

                  {formatUrgency(
                    selected.urgency_level,
                  )}

                </span>

              </div>

              <div className="sos-detail-grid">

                <div className="sos-detail-item">

                  <span>
                    Request ID
                  </span>

                  <strong>
                    {selected.id}
                  </strong>

                </div>

                <div className="sos-detail-item">

                  <span>
                    Patient
                  </span>

                  <strong>
                    {selectedUser?.full_name ??
                      "Unknown user"}
                  </strong>

                </div>

                <div className="sos-detail-item">

                  <span>
                    Email
                  </span>

                  <strong>
                    {selectedUser?.email ??
                      "Unavailable"}
                  </strong>

                </div>

                <div className="sos-detail-item">

                  <span>
                    User ID
                  </span>

                  <strong>
                    {selected.user_id}
                  </strong>

                </div>

                <div className="sos-detail-item">

                  <span>
                    Blood Group
                  </span>

                  <strong>
                    {selectedBloodGroup?.code ??
                      selectedBloodGroup?.name ??
                      "Unavailable"}
                  </strong>

                </div>

                <div className="sos-detail-item">

                  <span>
                    Units Required
                  </span>

                  <strong>
                    {selected.units_required}
                  </strong>

                </div>

                <div className="sos-detail-item">

                  <span>
                    Location
                  </span>

                  <strong>
                    {selectedLocation}
                  </strong>

                </div>

                <div className="sos-detail-item">

                  <span>
                    Created
                  </span>

                  <strong>
                    {formatDate(
                      selected.created_at,
                    )}
                  </strong>

                </div>

                <div className="sos-detail-item">

                  <span>
                    Location Timestamp
                  </span>

                  <strong>
                    {formatDate(
                      selected.location_timestamp,
                    )}
                  </strong>

                </div>

                <div className="sos-detail-item">

                  <span>
                    GPS Accuracy
                  </span>

                  <strong>
                    {selected.gps_accuracy !==
                    null
                      ? `${selected.gps_accuracy.toFixed(
                          1,
                        )} m`
                      : "Unavailable"}
                  </strong>

                </div>

              </div>

              {selected.description && (

                <div className="sos-detail-description">

                  <span>
                    Description
                  </span>

                  <p>
                    {selected.description}
                  </p>

                </div>

              )}

              {/* =========================================
                  OSM LOCATION
                  ========================================= */}

              <div className="sos-location-details">

                <div className="sos-section-heading">

                  <div>

                    <span>
                      LOCATION
                    </span>

                    <h3>
                      OpenStreetMap Location
                    </h3>

                  </div>

                </div>

                {hasCoordinates(
                  selected,
                ) ? (

                  <>

                    <div className="sos-coordinates">

                      <div>

                        <span>
                          Latitude
                        </span>

                        <strong>
                          {formatCoordinate(
                            selected.latitude,
                          )}
                        </strong>

                      </div>

                      <div>

                        <span>
                          Longitude
                        </span>

                        <strong>
                          {formatCoordinate(
                            selected.longitude,
                          )}
                        </strong>

                      </div>

                    </div>

                    {selectedOsmEmbedUrl && (

                      <div
                        className="sos-osm-map"
                        style={{
                          width: "100%",
                          height: "320px",
                          marginTop: "18px",
                          overflow: "hidden",
                          borderRadius: "14px",
                          border:
                            "1px solid var(--lifelynk-border, #e5e7eb)",
                          background:
                            "var(--lifelynk-surface, #f8fafc)",
                        }}
                      >

                        <iframe
                          title="Emergency SOS OpenStreetMap location"
                          src={
                            selectedOsmEmbedUrl
                          }
                          width="100%"
                          height="320"
                          style={{
                            display: "block",
                            width: "100%",
                            height: "320px",
                            border: 0,
                          }}
                          loading="lazy"
                          referrerPolicy="strict-origin-when-cross-origin"
                        />

                      </div>

                    )}

                    {selectedOsmUrl && (

                      <a
                        href={
                          selectedOsmUrl
                        }
                        target="_blank"
                        rel="noopener noreferrer"
                        className="sos-map-link"
                        style={{
                          display:
                            "inline-flex",
                          marginTop:
                            "14px",
                        }}
                      >
                        Open in OpenStreetMap
                      </a>

                    )}

                  </>

                ) : (

                  <p className="sos-no-location">
                    No GPS coordinates are
                    available for this SOS
                    request.
                  </p>

                )}

              </div>

            </div>

            {/* =========================================
                ACTIONS
                ========================================= */}

            <div className="sos-modal-footer">

              <div className="sos-action-group">

                {canMatch(
                  selected.status,
                ) && (

                  <button
                    type="button"
                    className="sos-action-button sos-action-activate"
                    disabled={
                      actionLoading !==
                      null
                    }
                    onClick={() =>
                      handleStatusUpdate(
                        selected,
                        "matched",
                        "MATCHED",
                      )
                    }
                  >
                    {actionLoading ===
                    "MATCHED"
                      ? "Accepting..."
                      : "Accept SOS"}
                  </button>

                )}

                {canStartResponse(
                  selected.status,
                ) && (

                  <button
                    type="button"
                    className="sos-action-button sos-action-activate"
                    disabled={
                      actionLoading !==
                      null
                    }
                    onClick={() =>
                      handleStatusUpdate(
                        selected,
                        "in_progress",
                        "IN_PROGRESS",
                      )
                    }
                  >
                    {actionLoading ===
                    "IN_PROGRESS"
                      ? "Starting..."
                      : "Start Response"}
                  </button>

                )}

                {canComplete(
                  selected.status,
                ) && (

                  <button
                    type="button"
                    className="sos-action-button sos-action-resolve"
                    disabled={
                      actionLoading !==
                      null
                    }
                    onClick={() =>
                      handleStatusUpdate(
                        selected,
                        "completed",
                        "COMPLETED",
                      )
                    }
                  >
                    {actionLoading ===
                    "COMPLETED"
                      ? "Completing..."
                      : "Mark Completed"}
                  </button>

                )}

                {canCancel(
                  selected.status,
                ) && (

                  <button
                    type="button"
                    className="sos-action-button sos-action-cancel"
                    disabled={
                      actionLoading !==
                      null
                    }
                    onClick={() =>
                      handleStatusUpdate(
                        selected,
                        "cancelled",
                        "CANCELLED",
                      )
                    }
                  >
                    {actionLoading ===
                    "CANCELLED"
                      ? "Cancelling..."
                      : "Cancel SOS"}
                  </button>

                )}

              </div>

              {!canMatch(
                selected.status,
              ) &&
                !canStartResponse(
                  selected.status,
                ) &&
                !canComplete(
                  selected.status,
                ) &&
                !canCancel(
                  selected.status,
                ) && (

                  <span className="sos-action-complete">
                    This SOS request is
                    closed. No further
                    actions are available.
                  </span>

                )}

              <button
                type="button"
                className="sos-modal-secondary-button"
                onClick={closeModal}
                disabled={
                  actionLoading !==
                  null
                }
              >
                Close
              </button>

            </div>

          </div>

        </div>

      )}

    </div>
  );
}